# Bare minimal configuration that supports 4 + 2 EC code profile for Multi-Site.
---
globals:
  - ceph-cluster:
      name: ceph-rgw1

      node1:
        role:
          - installer
          - mgr
          - mon
          - grafana

      node2:
        disk-size: 20
        no-of-volumes: 4
        role:
          - mgr
          - mon
          - osd

      node3:
        disk-size: 20
        no-of-volumes: 4
        role:
          - mon
          - osd
          - rgw

      node4:
        disk-size: 20
        no-of-volumes: 4
        role:
          - osd
          - rgw

      node5:
        role:
          - client

  - ceph-cluster:
      name: ceph-rgw2

      node1:
        role:
          - installer
          - mgr
          - mon
          - grafana

      node2:
        disk-size: 20
        no-of-volumes: 4
        role:
          - mgr
          - mon
          - osd

      node3:
        disk-size: 20
        no-of-volumes: 4
        role:
          - mon
          - osd
          - rgw

      node4:
        disk-size: 20
        no-of-volumes: 4
        role:
          - osd
          - rgw

      node5:
        role:
          - client
