#===============================================================================================
# Suite: nvme_cali_1admin_6node_2client.yaml
# Conf: conf/reef/baremetal/nvme_cali_1admin_6node_2client.yaml
# UPI test cases for
#    - Bootstrap
#    - Host management
#    - Service deployment
#    - Client Configuration
#===============================================================================================
tests:
  - test:
      abort-on-fail: true
      desc: Install software pre-requisites for cluster deployment.
      module: install_prereq.py
      name: setup pre-requisites

  - test:
      name: Deploy cluster using cephadm
      desc: bootstrap and deploy services
      module: test_cephadm.py
      polarion-id: CEPH-83573713
      config:
        steps:
          - config:
              command: bootstrap
              service: cephadm
              args:
                mon-ip: node1
                orphan-initial-daemons: true
                registry-url: registry.redhat.io
                allow-fqdn-hostname: true
                allow-overwrite: true
              base_cmd_args:
                verbose: true
          - config:
              command: add_hosts
              service: host
              args:
                attach_ip_address: true
                labels: apply-all-labels
          - config:
              command: apply
              service: mgr
              args:
                placement:
                  label: mgr
          - config:
              command: apply
              service: mon
              args:
                placement:
                  label: mon
      destroy-cluster: false
      abort-on-fail: true

  - test:
      name: OSD Service deployment with spec
      desc: Add OSD service using spec file.
      module: test_cephadm.py
      polarion-id: CEPH-83573746
      config:
        steps:
          - config:
              command: apply_spec
              service: orch
              specs:
                - service_type: osd
                  service_id: node1to6
                  placement:
                    nodes:
                    - node1
                    - node2
                    - node3
                    - node4
                    - node5
                    - node6
                    - node7
                    - node9
                  spec:
                    data_devices:
                      model: "PERC H755 Front"
                    db_devices:
                      # model: "Dell Ent NVMe CM6 MU 1.6TB"
                      paths:
                      - /dev/nvme0n1
                    encrypted: "true"                     # boolean as string

  - test:
      abort-on-fail: true
      config:
        command: add
        copy_admin_keyring: true
        id: client.1
        install_packages:
          - ceph-common
        node: node11
      desc: Configure the client-1
      destroy-cluster: false
      module: test_client.py
      name: configure client

  - test:
      abort-on-fail: true
      config:
        command: add
        copy_admin_keyring: true
        id: client.1
        install_packages:
          - ceph-common
        node: node12
      desc: Configure the client-2
      destroy-cluster: false
      module: test_client.py
      name: configure client

  - test:
      abort-on-fail: true
      config:
        rbd_pool: rbd
        do_not_create_image: true
        rep-pool-only: true
        rep_pool_config:
          pool: rbd
        install: true                           # Run SPDK with all pre-requisites
        cleanup:
          - pool
          - gateway
          - initiators
        gw_nodes:
          - node7
          - node8
        subsystems:                             # Configure subsystems with all sub-entities
          - nqn: nqn.2016-06.io.spdk:cnode1
            serial: 1
            bdevs:
            - count: 2
              size: 20G
              lb_group: node7
            listener_port: 4420
            listeners:
              - node7
              - node8
            allow_host: "*"
          - nqn: nqn.2016-06.io.spdk:cnode2
            serial: 2
            bdevs:
            - count: 2
              size: 20G
              lb_group: node8
            listener_port: 4420
            listeners:
              - node7
              - node8
            allow_host: "*"
        initiators:                             # Configure Initiators with all pre-req
          - nqn: connect-all
            listener_port: 4420
            node: node11
        fault-injection-methods:                # Failure induction
          - tool: systemctl
            nodes: node7
      desc: NVMEoF failover-failback test via systemctl rpm tool
      destroy-cluster: false
      module: test_ceph_nvmeof_high_availability.py
      name: NVMeoF 2-GW HA failover-failback via systemctl
      polarion-id: CEPH-83588636
