# Use cluster-conf file: conf/rados/stretch-mode-host-location-attrs.yaml
# Suite contains tests related to election strategy and Stretched mode
---
tests:
  - test:
      name: Install ceph pre-requisites
      desc: installation of ceph pre-requisites
      module: install_prereq.py
      abort-on-fail: true

  - test:
      name: Cephadm Bootstrap with apply-spec
      desc: Apply spec in Bootstrap with host location attributes
      module: test_bootstrap.py
      polarion-id: CEPH-83575289
      config:
        command: bootstrap
        base_cmd_args:
          verbose: true
        args:
          registry-json: registry.redhat.io
          mon-ip: node1
          orphan-initial-daemons: true
          skip-dashboard: true
          ssh-user: cephuser
          apply-spec:
            - service_type: host
              address: true
              labels: apply-all-labels
              nodes:
                - node1
            - service_type: host
              address: true
              labels: apply-all-labels
              nodes:
                - node2
                - node3
              location:
                root: default
                datacenter: DC1
            - service_type: host
              address: true
              labels: apply-all-labels
              nodes:
                - node4
                - node5
              location:
                root: default
                datacenter: DC2
            - service_type: mon
              placement:
                label: mon
            - service_type: mgr
              placement:
                label: mgr
      destroy-cluster: false
      abort-on-fail: true

  - test:
      name: Service deployment with spec
      desc: Add OSD services using spec file.
      module: test_cephadm.py
      polarion-id: CEPH-83573746
      config:
        steps:
          - config:
              command: apply_spec
              service: orch
              validate-spec-services: true
              specs:
                - service_type: osd
                  service_id: all-available-devices
                  placement:
                    label: osd
                  spec:
                    data_devices:
                      all: "true"                         # boolean as string
          - config:
              command: shell
              args: # display OSD tree
                - "ceph osd tree"

  - test:
      name: MDS Service deployment with spec
      desc: Add MDS services using spec file
      module: test_cephadm.py
      polarion-id: CEPH-83574728
      config:
        steps:
          - config:
              command: shell
              args: # arguments to ceph orch
                - ceph
                - fs
                - volume
                - create
                - cephfs
          - config:
              command: apply_spec
              service: orch
              validate-spec-services: true
              specs:
                - service_type: mds
                  service_id: cephfs
                  placement:
                    label: mds

  - test:
      name: RGW Service deployment
      desc: RGW Service deployment
      module: test_cephadm.py
      polarion-id: CEPH-83574728
      config:
        steps:
          - config:
              command: apply
              service: rgw
              pos_args:
                - rgw.1
              args:
                placement:
                  label: rgw

  - test:
      name: Configure client admin
      desc: Configures client admin node on cluster
      module: test_client.py
      polarion-id:
      config:
        command: add
        id: client.1                      # client Id (<type>.<Id>)
        nodes:
          - node6:
              release: 7
        install_packages:
          - ceph-common
          - ceph-base
        copy_admin_keyring: true          # Copy admin keyring to node
        caps: # authorize client capabilities
          mon: "allow *"
          osd: "allow *"
          mds: "allow *"
          mgr: "allow *"
      abort-on-fail: true
