tests:
  - test:
      config:
        ansi_config:
          ceph_origin: distro
          ceph_stable: true
          ceph_stable_release: nautilus
          ceph_stable_rh_storage: true
          ceph_test: true
          ceph_conf_overrides:
            client:
              rgw crypt require ssl: false
              rgw crypt s3 kms encryption keys: testkey-1=YmluCmJvb3N0CmJvb3N0LWJ1aWxkCmNlcGguY29uZgo=
                testkey-2=aWIKTWFrZWZpbGUKbWFuCm91dApzcmMKVGVzdGluZwo=
            global:
              mon_max_pg_per_osd: 1024
              osd_default_pool_size: 2
              osd_pool_default_pg_num: 64
              osd_pool_default_pgp_num: 64
            mon:
              mon_allow_pool_delete: true
          osd_scenario: collocated
          journal_size: 1024
      polarion-id: CEPH-83571503
      name: "containerized ceph ansible"
