---
name: Configuration suite file for image operations on rbd client.
must_pass: true
parallel: false
tests:
    - runs_on: ceph-cluster1
      parallel: true
      config:
          - test:
                name: Running suite to bootstrap cluster.
                desc: configuration to bootstrap cluster.
                suite: misc/test_bootstrap_cluster.yaml
          - test:
                name: rbd node deployment
                desc: Configuration to deploy rbd node in cluster
                module: workflow.py
                steps:
                    - method: apply
                      class: Orch
                      component: ceph
                      args:
                          service_type: rbd-mirror
                          placement:
                              node:
                                  - node5
          - test:
                name: Creation of pool.
                desc: configuration for the creation of mirror pool.
                module: workflow.py
                steps:
                    - method: create
                      class: Pool
                      component: ceph
                      args:
                          pool_name: mirror_test
          - test:
                name: Creation of image.
                desc: configuration for the creation of block device image.
                module: workflow.py
                steps:
                    - method: create
                      class: Rbd
                      component: rbd
                      args:
                          image_spec: mirror_test/image_1
                          image-feature: journaling
          - test:
                name: enable pool mirroring
                desc: configuration to Enable Pool mirroring.
                module: workflow.py
                steps:
                    - method: enable
                      class: Pool
                      component: rbd_mirror
                      args:
                          pool_name: mirror_test
                          mode: pool
    - runs_on: ceph-cluster2
      parallel: true
      config:
          - test:
                name: Running suite to bootstrap cluster.
                desc: configuration to bootstrap cluster.
                suite: misc/test_bootstrap_cluster.yaml
          - test:
                name: rbd node deployment
                desc: Configuration to deploy rbd node in cluster
                module: workflow.py
                steps:
                    - method: apply
                      class: Orch
                      component: ceph
                      args:
                          service_type: rbd-mirror
                          placement:
                              node:
                                  - node5
          - test:
                name: Creation of pool.
                desc: configuration for the creation of mirror pool.
                module: workflow.py
                steps:
                    - method: create
                      class: Pool
                      component: ceph
                      args:
                          pool_name: mirror_test
          - test:
                name: Creation of image.
                desc: configuration for the creation of block device image.
                module: workflow.py
                steps:
                    - method: create
                      class: Rbd
                      component: rbd
                      args:
                          image_spec: mirror_test/image_1
                          image-feature: journaling
          - test:
                name: enable pool mirroring
                desc: configuration to Enable Pool mirroring.
                module: workflow.py
                steps:
                    - method: enable
                      class: Pool
                      component: rbd_mirror
                      args:
                          pool_name: mirror_test
                          mode: pool
          - test:
                name: Enable sleep Operation
                desc: sleep
                module: utils
                steps:
                    - method: sleep
                      args:
                          sleep_time: 30
          - test:
                name: Check image info on secondary
                desc: Configuration to check image info on secondary.
                module: workflow.py
                steps:
                    - method: info
                      class: Rbd
                      component: rbd
                      args:
                          image_spec: mirror_test/image_1
