name: Configuration suite file for configuring client node.
must_pass: true
tests:
  - runs_on: ceph-cluster1
    parallel: false
    config:
      - test:
          name: cluster configuration
          desc: Configuration for ceph client node
          module: workflow.py
          steps:
            - method: create_directory
              module: utils.py
              role: client
              args:
                path: /etc
                name: ceph
            - method: get-or-create
              class: auth
              component: ceph
              shell: true
              args:
                caps:
                  mon: allow *
                  osd: allow *
                  mds: allow *
                  mgr: allow *
                entity: client.1
                output_file: /etc/ceph/auth
              role: client
            - method: write_to_remote_file
              module: utils.py
              role: client
              args:
                destination_path: /etc/ceph/ceph.client1.keyring
                source_path: /etc/ceph/auth
            - method: generate-minimal-conf
              class: config
              role: client
              component: ceph
              args:
                path: /etc/ceph/ceph.conf
            - method: get
              class: auth
              role: client
              component: ceph
              args:
                entity: client.admin
            - method: write_to_remote_file
              module: utils.py
              role: client
              args:
                destination_path: /etc/ceph/ceph.client.admin.keyring
                source_path:
                  load_input_result: "cluster configuration.step5"
            - method: write_to_remote_file
              module: utils.py
              role: installer
              args:
                source_node: ceph-cluster1-openstack-openstacknode-1
                source_path: /etc/ceph/auth
                destination_path: /etc/ceph/ceph.client.1.keyring
                destination_node: ceph-cluster1-openstack-openstacknode-2
